// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLkDT9crX2_NUydedSfNyfKGzwWpplrA',
    appId: '1:633659356999:android:27206e72a54e3625113e62',
    messagingSenderId: '633659356999',
    projectId: 'mynotes-asultan',
    storageBucket: 'mynotes-asultan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjTjNOcpZXIUuqmq8GOJg6eViUvbRYLiQ',
    appId: '1:633659356999:ios:aa63257e64404989113e62',
    messagingSenderId: '633659356999',
    projectId: 'mynotes-asultan',
    storageBucket: 'mynotes-asultan.firebasestorage.app',
    iosBundleId: 'com.adeel4sultan.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzHJNpxlroIxoorb2Iwy6HDJ0zu8Qb1bQ',
    appId: '1:633659356999:web:7a9eca60e6bf5cf5113e62',
    messagingSenderId: '633659356999',
    projectId: 'mynotes-asultan',
    authDomain: 'mynotes-asultan.firebaseapp.com',
    storageBucket: 'mynotes-asultan.firebasestorage.app',
  );
}
